accounts/urls.py
from django.urls import path
from pacientes import views
from django.contrib.auth.urls import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='pacientes/home.html'), name='logout', kwargs={'next_page':'/'}),
]

pacientes/urls.py
from django.urls import path
from pacientes import views
from django.contrib.auth.urls import views as auth_views

app_name = 'pacientes'

urlpatterns = [
    path('formulario/', views.PatientCreateView.as_view(), name='formulario'),
    path('lista/', views.PatientListView.as_view(), name='lista'),
]

sesi/urls.py
from django.contrib import admin
from django.urls import path, include
from pacientes import views
urlpatterns = [
    path('', views.Home.as_view(template_name='pacientes/home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('sesi/', include('pacientes.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

pacientes/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    situation = models.CharField(max_length=250, null=True)

    def __str__(self):
        return self.situation

class Patiente(models.Model):
    name = models.CharField(max_length=250)
    age = models.PositiveIntegerField()
    rg = models.IntegerField(null=True)
    cpf = models.IntegerField(null=True)
    address = models.CharField(max_length=250, null=True)
    city = models.CharField(max_length=250, null=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Employee(models.Model):
    name = models.CharField(max_length=250, null=True)
    cpf = models.PositiveIntegerField()
    senha = models.CharField(max_length=250)


    def __str__(self):
        return self.name

pacientes/forms.py
from django import forms
from pacientes.models import Patiente, Employee

class PatienteForm(forms.ModelForm):
    class Meta():
        model = Patiente
        fields = ('name', 'age', 'cpf', 'rg', 'address', 'city', 'status')


# class EmployeeForm(forms.ModelForm):
#     class Meta():
#         model = Employee
#         fields = ('cpf', 'senha')

accounts/views.py
from django.shortcuts import render

# Create your views here.

pacientes/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, ListView
from pacientes.models import Patiente, Employee
from pacientes.forms import PatienteForm
from django.urls import reverse_lazy
# Create your views here.
class Home(TemplateView):
    template_name = 'pacientes/home.html'

class PatientCreateView(CreateView):
    model = Patiente
    form_class = PatienteForm
    success_url = reverse_lazy('home')
    template_name = 'pacientes/formulario.html'

class PatientListView(ListView):
    context_object_name = 'patients'
    model = Patiente

templates/pacientes/base.html
<!DOCTYPE html>
{% load static %}
<html lang='pt-br'>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static '/css/master.css' %}">
    <link rel="stylesheet" href="{% static '/css/home.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/formulario.css' %}">
  </head>
  <body>
    <div id="page-home">
      <div class="content">
        <header>
          <nav class="navbar">
            <a href="">
              <img id="logo" src="{% static 'images/logo.jpg' %}">
            </a>
            <div class="on">
              {% if user.is_authenticated %}
              <a href="{% url 'home' %}">Inicio</a>
              <a href="{% url 'pacientes:formulario' %}">Formulário</a>
              <a href="{% url 'pacientes:lista' %}">Pacientes</a>
              <a href="{% url 'admin:index' %}">Admin</a>
              <a href="{% url 'logout'%}">Sair</a>
              {% else %}
              <a href="{% url 'login' %}">
                <span> Entrar </span>
              </a>
              {% endif %}
            </div>
          </nav>
        </header>
        <main>
          {% block content %}
          {% endblock %}
        </main>
      </div>
    </div>
  </body>
</html>

templates/pacientes/formulario.html
{% extends 'pacientes/base.html' %}
{% load static %}
{% block content %}
  <div class="formu">
    <form method="POST">
      <h1>Formulário para cadastro de pacientes</h1>
      {% csrf_token %}
      <label for="{{ form.name.id_for_label }}">Nome:</label>
      {{ form.name }}
      <div class="field-group">
        <div class="field">
          <label for="{{ form.age.id_for_label }}">Idade:</label>
          {{ form.age }}
        </div>
        <div class="field">
          <label for="{{ form.cpf.id_for_label }}">CPF:</label>
          {{ form.cpf }}
        </div>
        <div class="field">
          <label for="{{ form.rg.id_for_label }}">RG:</label>
          {{ form.rg }}
        </div>
      </div>
      <label for="{{ form.address.id_for_label }}">Endereço:</label>
      {{ form.address }}
      <label for="{{ form.city.id_for_label }}">Cidade:</label>
      {{ form.city }}
      <label id="status" for="{{ form.status.id_for_label }}">Status:</label>
      {{ form.status }}
      <input id="botao" type="submit" value="Registrar">
    </form>
  </div>
  <!-- <form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit"  value="Registrar">
  </form> -->


{% endblock %}

templates/pacientes/home.html
{% extends 'pacientes/base.html '%}
{% load static %}
<title>Home</title>
{% block content %}
    <h1>Sindromes Gripais!</h1>
    <p>O site tem como objetivo guardar os dados e ter um controle maior
      sobre a quantidade de pacientes testados dentro da unidade
    </p>
{% endblock %}

templates/pacientes/patiente_list.html
{% extends 'pacientes/base.html' %}
<title>Dados</title>
{% block content %}
  {% if patient in patients %}
    <h1> Lista de pacientes </h1>
    <table border="1">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Teste</th>
        </tr>
      </thead>
      <tbody>
          {% for patient in patients %}
          <tr>
            <td>{{patient.name}}</td>
            <td>{{patient.status}}</td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
  {% else %}
  <h2> Não há pacientes registrado </h2>
  {% endif %}
{% endblock %}